FROM python:3.11-slim

RUN apt-get update && apt-get install -y tesseract-ocr && apt-get clean

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 5000

CMD ["python", "extractor.py"]
